### ISSUE TITLE
Does pool liquidity L actually change on mints and burns?

### ISSUE THREAD

**Issue by timnugent** [Jeiwan/uniswapv3-code#2]
Just looking at this line, where pool liquidity is updated:

https://github.com/Jeiwan/uniswapv3-code/blob/milestone_1/src/UniswapV3Pool.sol#L111

I can't really see the equivalent line in the actual pool contract. And running some subgraph queries before and after mints/burns, L doesn't seem to change.

Can you explain what's going on here?

Thanks

**Comment by Jeiwan** [comment]
Here it is:
https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L361
This happens when modifying a position that's currently engaged (the current price is within its boundaries).

Moreover, liquidity is updated during swaps when positions get engaged/disengaged
https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L755
